package com.et.greendaodemo.database;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.et.greendaodemo.database.KeyBean;
import com.et.greendaodemo.database.UserBean;

import com.et.greendaodemo.database.KeyBeanDao;
import com.et.greendaodemo.database.UserBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig keyBeanDaoConfig;
    private final DaoConfig userBeanDaoConfig;

    private final KeyBeanDao keyBeanDao;
    private final UserBeanDao userBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        keyBeanDaoConfig = daoConfigMap.get(KeyBeanDao.class).clone();
        keyBeanDaoConfig.initIdentityScope(type);

        userBeanDaoConfig = daoConfigMap.get(UserBeanDao.class).clone();
        userBeanDaoConfig.initIdentityScope(type);

        keyBeanDao = new KeyBeanDao(keyBeanDaoConfig, this);
        userBeanDao = new UserBeanDao(userBeanDaoConfig, this);

        registerDao(KeyBean.class, keyBeanDao);
        registerDao(UserBean.class, userBeanDao);
    }
    
    public void clear() {
        keyBeanDaoConfig.clearIdentityScope();
        userBeanDaoConfig.clearIdentityScope();
    }

    public KeyBeanDao getKeyBeanDao() {
        return keyBeanDao;
    }

    public UserBeanDao getUserBeanDao() {
        return userBeanDao;
    }

}
