package com.et.greendaodemo.database;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "KEY_BEAN".
*/
public class KeyBeanDao extends AbstractDao<KeyBean, String> {

    public static final String TABLENAME = "KEY_BEAN";

    /**
     * Properties of entity KeyBean.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property KeyName = new Property(0, String.class, "keyName", false, "KEYNAME");
        public final static Property KeyBalance = new Property(1, String.class, "keyBalance", false, "KEYBALANCE");
        public final static Property KeyId = new Property(2, String.class, "keyId", true, "KEYID");
    }


    public KeyBeanDao(DaoConfig config) {
        super(config);
    }
    
    public KeyBeanDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"KEY_BEAN\" (" + //
                "\"KEYNAME\" TEXT," + // 0: keyName
                "\"KEYBALANCE\" TEXT," + // 1: keyBalance
                "\"KEYID\" TEXT PRIMARY KEY NOT NULL );"); // 2: keyId
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"KEY_BEAN\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, KeyBean entity) {
        stmt.clearBindings();
 
        String keyName = entity.getKeyName();
        if (keyName != null) {
            stmt.bindString(1, keyName);
        }
 
        String keyBalance = entity.getKeyBalance();
        if (keyBalance != null) {
            stmt.bindString(2, keyBalance);
        }
 
        String keyId = entity.getKeyId();
        if (keyId != null) {
            stmt.bindString(3, keyId);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, KeyBean entity) {
        stmt.clearBindings();
 
        String keyName = entity.getKeyName();
        if (keyName != null) {
            stmt.bindString(1, keyName);
        }
 
        String keyBalance = entity.getKeyBalance();
        if (keyBalance != null) {
            stmt.bindString(2, keyBalance);
        }
 
        String keyId = entity.getKeyId();
        if (keyId != null) {
            stmt.bindString(3, keyId);
        }
    }

    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2);
    }    

    @Override
    public KeyBean readEntity(Cursor cursor, int offset) {
        KeyBean entity = new KeyBean( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // keyName
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // keyBalance
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2) // keyId
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, KeyBean entity, int offset) {
        entity.setKeyName(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setKeyBalance(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setKeyId(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
     }
    
    @Override
    protected final String updateKeyAfterInsert(KeyBean entity, long rowId) {
        return entity.getKeyId();
    }
    
    @Override
    public String getKey(KeyBean entity) {
        if(entity != null) {
            return entity.getKeyId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(KeyBean entity) {
        return entity.getKeyId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
